name: star-nf
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - sra-tools=2.9.1
  - entrez-direct=7.70
  - parallel-fastq-dump=0.6.3
  - samtools=1.9
  - bioconductor-biocinstaller=1.28.0
  - readline=6.2
  - bioconductor-rsubread=1.28.0
